### ISSUE TITLE
Strict mode violation

### ISSUE THREAD

**Issue by ber4444** [signalfx/splunk-otel-android#507] opened 2023-03-24 00:34 UTC
```
StrictMode policy violation; ~duration=94 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=196631 violation=2
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                 	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:240)
                 	at java.io.File.isDirectory(File.java:804)
                 	at java.io.File.toURI(File.java:698)
                 	at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:52)
                 	at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:532)
                 	at dalvik.system.DexPathList$Element.findResource(DexPathList.java:568)
                 	at dalvik.system.DexPathList.findResource(DexPathList.java:440)
                 	at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:74)
                 	at java.lang.ClassLoader.getResource(ClassLoader.java:793)
                 	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:977)
                 	at java.lang.Class.getResourceAsStream(Class.java:2095)
                 	at io.opentelemetry.sdk.resources.Resource.readVersion(Resource.java:116)
                 	at io.opentelemetry.sdk.resources.Resource.<clinit>(Resource.java:57)
                 	at io.opentelemetry.sdk.resources.Resource.getDefault(Resource.java:70)
                 	at io.opentelemetry.rum.internal.OpenTelemetryRumBuilder.<init>(OpenTelemetryRumBuilder.java:44)
                 	at io.opentelemetry.rum.internal.OpenTelemetryRum.builder(OpenTelemetryRum.java:31)
                 	at com.splunk.rum.RumInitializer.initialize(RumInitializer.java:94)
                 	at com.splunk.rum.SplunkRum.initialize(SplunkRum.java:111)
                 	at com.splunk.rum.SplunkRumBuilder.build(SplunkRumBuilder.java:317)
```
using `com.splunk:splunk-otel-android:1.0.0`

**Comment by breedx-splk** [comment] 2023-04-06 21:12
Interesting, thanks for the info. It looks like the OpenTelemetry sdk is attempting to read its version number from a file in storage, typically on the classpath, which in java apps means it's resource file, but breaks on strict mode in android. I'll see if I can reproduce.

**Comment by breedx-splk** [comment] 2023-04-06 21:46
@ber4444 Ok my understanding here is that StrictMode is a tool for helping developers to understand when there app is doing too much work on the main (UI) thread. I'm a bit concerned that if we just just simply backgrounded the SDK creation work that we might get into a pickle where later lifecycle components are expecting to use OpenTelemetry before the SDK has finished initializing.

Open to other thoughts, approaches. Thanks.

**Comment by ber4444** [comment] 2023-04-22 05:51
SplunkRum.isInitialized is available

**Comment by breedx-splk** [comment] 2023-05-04 21:26
https://github.com/open-telemetry/opentelemetry-java/pull/5365 should help with this. It's been merged, but will not be available until the next otel java core release (1.26.0).

**Comment by breedx-splk** [comment] 2023-06-09 18:12
@ber4444 Can you confirm that this is fixed for you on `main` tip? Thanks!

**Comment by breedx-splk** [comment] 2023-09-06 23:53
@ber4444 Can you test again with the latest version (v1.1.1)? Thanks!

**Comment by breedx-splk** [comment] 2023-10-17 20:01
Please reopen if this is still an issue.

**Closed by breedx-splk** 2023-10-17 20:01 UTC
