### ISSUE TITLE
ANR's are not logged properly

### ISSUE THREAD

**Issue by ber4444** [signalfx/splunk-otel-android#750] opened 2024-01-31 22:27 UTC
We have a lot of these reports, as you can see it's all messed up:
<img width="349" alt="Screenshot 2024-01-31 at 2 26 34 PM" src="https://github.com/signalfx/splunk-otel-android/assets/205867/98a359da-e772-497b-b00e-54c677d7dc88">
Raw details of the event:
```
Error
ANR
!
603µs
Span ID c566c1f2f178473b
Operation       ANR
Tags
_sf_ua_browserName
OkHttp
_sf_ua_browserVersion
4.12.0
_splunk_operation
ANR
app.build.type
release
app.version
1.0.9-qa
component
error
device.model.identifier
IN2017
device.model.name
IN2017
error
true
exception.message
Method)
exception.stacktrace
android.os.BinderProxy.transactNative(Native Method)
android.os.BinderProxy.transact(BinderProxy.java:678)
android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:4877)
com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:187)
zd.k0.uncaughtException(Unknown Source:55)
io.opentelemetry.android.instrumentation.crash.CrashReportingExceptionHandler.uncaughtException(Unknown Source:20)
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
com.android.internal.os.RuntimeInitExtImpl.uncaughtExceptionExt(RuntimeInitExtImpl.java:44)
com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:140)
java.lang.Thread.dispatchUncaughtException(Thread.java:2300)
exception.type
Method)
net.host.connection.type
wifi
orgId
FJ41tMKAcAA
os.name
Android
os.type
linux
os.version
13
otel.library.name
io.opentelemetry.anr
otel.scope.name
io.opentelemetry.anr
otel.status_code
ERROR
rum.sdk.version
1.2.0
screen.name
unknown
```

**Comment by breedx-splk** [comment] 2024-02-07 19:05
Hey @ber4444 thanks for the report. That doesn't look great. Where are you getting the "raw event" data from? Is the above getting partially mangled through copy/pasting?

**Comment by ber4444** [comment] 2024-02-07 20:36
I copy-pasted from the Splunk dashboard but there is a screenshot which I posted as well. So instead of a helpful error event, you get junk.

**Comment by breedx-splk** [comment] 2024-02-07 21:05
The screenshot you provided does not appear to contain the same information as the pasted text, perhaps it's taken from somewhere else? Can you either paste a screenshot of the same data or reformat the data? 

The only thing I can really see in the above is that it looks like the `exception.message` is set to `Method)`. Is that what you're referring to?

**Comment by ber4444** [comment] 2024-03-06 21:27
this bug is still happening, another example:
![Uploading Screenshot 2024-03-06 at 1.27.01 PM.png…]()

**Comment by ber4444** [comment] 2024-03-06 21:30
Or maybe it's intended, but `error.message` and `error.type` are missing, which causes the ANR to appear as a blank item in the main "Tag Spotlight" view

**Comment by breedx-splk** [comment] 2024-03-06 23:03
Hey @ber4444 thanks for testing it out again and reporting back. So I think you probably meant `exception.message` and `exception.type` in the above, right? Ok, so the thing with ANRs is that they are _not_ initiated by an exception being thrown. The instrumentation detects an ANR by checking in periodically with the main thread.

When it determines that an ANR has occurred, it does not generate an exception. It does synthesizes the ANR event that you screenshot above, and it does capture the stack for the main thread. The instrumentation does not synthesize an `exception.message` nor `exception.type`.

We have some code in our backend, however, that creates the `exception.message` and `exception.type` when there are exceptions included with some events. In the case of ANRs, the stacks are shaped slightly differently and that was causing the weird messages you saw originally. We've since fixed that problem and suppress those two fields for ANRs.

Hope that makes sense.

**Comment by ber4444** [comment] 2024-04-03 19:29
I'm cool with this:
<img width="922" alt="Képernyőfotó 2024-04-03 - du  12 28 05" src="https://github.com/signalfx/splunk-otel-android/assets/205867/15a63cf2-341e-4b61-a68a-ba3c39eff0c2">
What I'm struggling with, is this view:
<img width="477" alt="Képernyőfotó 2024-04-03 - du  12 27 28" src="https://github.com/signalfx/splunk-otel-android/assets/205867/a011fbd7-4aff-4660-a78a-5c4578dc7648">
as Error ID should have a human readable message, like for all other errors.

**Comment by ber4444** [comment] 2024-04-18 23:48
<img width="380" alt="Képernyőfotó 2024-04-18 - du  4 46 16" src="https://github.com/signalfx/splunk-otel-android/assets/205867/758e1c70-7246-43d7-824f-866019881536">
this is another aspect of the same thing - instead of a useful message, we see <other>. Need to go into individual user sessions to find the error, which in this case is
```
error	true
exception.message	An SSL error has occurred and a secure connection to the server cannot be made.
exception.type	NSURLError
```

**Comment by breedx-splk** [comment] 2024-04-19 01:00
Hey @ber4444 thanks again, but however, this isn't really an instrumentation concern caused by ANRs like in the title. Hopefully my previous comment has helped to explain why/how this is the case. This is more of a product/UI concern and we would therefore encourage you to open a [Splunk IDEA](https://ideas.splunk.com) on this and/or work with your account person to get the feedback in front of the right person. 

I'm going to close this issue, but if you feel like there are specific instrumentation concerns that can help with this situation please feel free to reopen.

**Closed by breedx-splk** 2024-04-19 01:00 UTC
